name: kind_teddy
services:
  main_app:
    cpu_shares: 50
    command: []
    container_name: Nudb
    deploy:
      resources:
        limits:
          memory: 2048M
    environment:
      - "WSS_URL=wss://nudb.nufat.id"
      - ADMIN_PASSWORD=secret123
      - ADMIN_USERNAME=admin
      - JWT_SECRET=Nurani110
      - NODE_ENV=production
      - PORT=8008
    hostname: Nudb
    image: nufat/nudb:latest
    labels:
      icon: https://icon.casaos.io/main/all/nudb.png
    ports:
      - target: 8008
        published: "8010"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/Nudb/data
        target: /app/data
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
x-casaos:
  author: self
  category: self
  hostname: nudb.nufat.id
  icon: https://icon.casaos.io/main/all/nudb.png
  index: /
  is_uncontrolled: false
  port_map: ""
  scheme: https
  store_app_id: kind_teddy
  title:
    custom: Nudb
