name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm install terser -g
          terser db.js -o db.min.js --compress --mangle
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Minify for release"