name: Auto Increment Release

on:
  push:
    branches: [ "main" ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        fetch-depth: 0  # Penting untuk mendapatkan semua tag

      - name: Minify JS
        run: |
          npm install terser -g
          terser db.js -o db.min.js --compress --mangle

      - name: Get Latest Tag
        id: get_version
        run: |
          # Dapatkan tag terakhir yang mengandung 'v' dan angka
          LATEST_TAG=$(git describe --tags --abbrev=0 --match "v[0-9]*.[0-9]*.[0-9]*" 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $LATEST_TAG"
          
          # Ekstrak angka versi dan increment patch version
          if [[ $LATEST_TAG =~ v([0-9]+)\.([0-9]+)\.([0-9]+) ]]; then
            MAJOR=${BASH_REMATCH[1]}
            MINOR=${BASH_REMATCH[2]}
            PATCH=$(( ${BASH_REMATCH[3]} + 1 ))
            NEW_VERSION="v$MAJOR.$MINOR.$PATCH"
          else
            NEW_VERSION="v1.0.0"  # Fallback jika tidak ada tag
          fi
          
          echo "New version: $NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.new_version }}
          name: "Release ${{ steps.get_version.outputs.new_version }}"
          files: |
            db.min.js
          body: |
            Auto-generated release
            Version: ${{ steps.get_version.outputs.new_version }}